### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by nkpz** [earksiinni/riot-control#1]
One of the more popular event dispatchers for Riot uses this name
https://github.com/jimsparkman/RiotControl

In a community this small, it's almost certain to cause confusion. I used `npm install riot-control` instead of `npm install riotcontrol` and was confused for about an hour before I realized that I hadn't even installed the package I was looking for.

**Comment by ersinakinci** [comment]
Wow. Talk about a n00b mistake. My b.

Changed everything to RiotFlow. npm install riotflow. Thanks for letting me know! I'm loving Riot and I hope to keep contributing to the community. Apologies to the crew over at RiotControl.
